### ISSUE TITLE
Error when launching streamlit app due to missing conf/local folder

### ISSUE THREAD

**Issue by ejwillemse** [WasteLabs/template_kedro_streamlit#4]
Cloning the repo as is does means there is not a `conf/local` folder, as needed by kedro. It then produces the following error when running the streamlit app:

```
ValueError: Given configuration path either does not exist or is not a valid directory: <path-to-project>/conf/local
```

Solution:

* include an empty `conf/local` folder with a `.gitkeep` file

**Comment by ejwillemse** [comment]
@ARashitov , I see there is already a gitignore exception specifically for this:

https://github.com/WasteLabs/template_kedro_streamlit/blob/6e1d6c784433ba839dcdc9eaee456b1befba6946/.gitignore#L218

any idea why the folder is not in the repo?

**Comment by ARashitov** [comment]
@ejwillemse  I used default `kedro init` command to setup repository and did't touch any configs. So, will reproduce it. If it's bug will fix it on kedro's  repository of cookiecutter submodule

**Comment by ejwillemse** [comment]
This bug is still present...

When cloning the repo, confo/local/ is not present which raises errors. Please investigate and fix ASAP.

To replicate, simply clone the repo and follow the readme instructions

**Comment by ARashitov** [comment]
@ejwillemse  Rows forced to ignore local in `.gitignore`:
```
[Bb]in
[Ii]nclude
[Ll]ib <- this
[Ll]ib64 <- this
[Ll]ocal <- this
[Ss]cripts
```

bug is fixed
